name = "theory-vibmehta"
main = "src/index.js"
compatibility_date = "2026-09-17"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "vibmehta-applications"
database_id = "f03a37ba-f4f1-43ac-a0be-7ba8f881585b"
migrations_dir = "migrations"

[[routes]]
pattern = "vibmehta.com"
custom_domain = true

[[routes]]
pattern = "www.vibmehta.com"
custom_domain = true

[vars]
TO_EMAIL = "vibhorfall@gmail.com"
FROM_EMAIL = "applications@vibmehta.com"
SITE_NAME = "Theory"
